FILE CSI DRIVER Implementation
IBM/ibm-vpc-file-csi-driver pull request #1
Opened 2021-06-17 16:43 UTC by sameshai

2021-06-18 05:23 UTC, sameshai commented
For details of test results refer https://ibm.box.com/s/fkfw38q3z12ixfhpcyzqmss3i5zk0m6n

2021-06-18 11:11 UTC, sameshai commented on deploy/kubernetes/driver/kubernetes/manifests/config-map.yaml
> +  IKS_ENABLED: "True"
We should remove IKS_ENABLED from open-source

2021-06-18 11:12 UTC, sameshai commented on deploy/kubernetes/driver/kubernetes/manifests/controller-server.yaml
> +            - "--sidecarEndpoint=$(SIDECAREP)"
Remove this sidecarEndpoint from open-source

2021-11-02 07:57 UTC, arahamad requested changes
please check the comments

2021-11-02 07:57 UTC, arahamad commented on deploy/kubernetes/driver/kubernetes/manifests/node-server.yaml
> +              value: /csi/csi-vpc-file.sock
verify and run this node service as non-root i.e update runAsUser: 1000, runAsNonRoot: false is also not required ---> next PR is also fine

2021-11-02 07:57 UTC, arahamad commented on deploy/kubernetes/driver/kubernetes/manifests/setup-vpc-file-sa.yaml
>     - name: bluemix-default-secret
can we create a new GHE to cleanup deployment and more restricted as per requirement for file and ready for Nov release

2021-11-02 07:57 UTC, arahamad commented on deploy/kubernetes/driver/kubernetes/overlays/dev/controller-server-images.yaml
> +          image: icr.io/ibm/ibm-vpc-file-csi-driver:v1.0.0
check in block addon and update it accordingly. --> next PR

2021-11-02 07:57 UTC, arahamad commented on examples/kubernetes/storageclass-secret.yaml
> +  csi.storage.k8s.io/fstype: "nfs"     # ext4 is the default filesytem used. The user can override this default
check and update in next PR

2021-11-02 07:57 UTC, arahamad commented on pkg/ibmcsidriver/constants.go
> +var SupportedFS = []string{"ext2", "ext3", "ext4", "nfs"}
not required --> remove in this PR

2021-11-02 07:57 UTC, arahamad commented on pkg/ibmcsidriver/controller.go
>  	PublishInfoNodeID = "node-id"
please check this is required for block, remove in accordingly, --> in this PR

2021-11-02 07:57 UTC, arahamad commented on pkg/ibmcsidriver/controller.go
> +	var isVolumeExist bool = false
write the flow in comments

2021-11-02 07:57 UTC, arahamad commented on pkg/ibmcsidriver/controller.go
> +	return nil, commonError.GetCSIError(ctxLogger, commonError.MethodUnimplemented, requestID, nil, "PublishVolume")
check this error code, it will be good if we return un-supported

2021-11-02 07:57 UTC, arahamad commented on pkg/ibmcsidriver/controller.go
> +		return nil, commonError.GetCSIError(ctxLogger, commonError.InternalError, requestID, nil)
pl check if we want to return as InternalError or specific error so that user can take action

2021-11-02 07:57 UTC, arahamad commented on pkg/ibmcsidriver/controller_helper_test.go
> +				VolumeCapabilities: []*csi.VolumeCapability{{AccessMode: &csi.VolumeCapability_AccessMode{Mode: csi.VolumeCapability_AccessMode_SINGLE_NODE_WRITER}}},
remove un-used code in the unit tests as well --> may be next PR

2021-11-02 07:57 UTC, arahamad commented on pkg/ibmcsidriver/ibm_csi_driver.go
> +		csi.VolumeCapability_AccessMode_MULTI_NODE_MULTI_WRITER,
please check the vpc capabilities and add the same here

2021-11-02 07:57 UTC, arahamad commented on pkg/ibmcsidriver/ibm_csi_driver.go
>  		csi.NodeServiceCapability_RPC_GET_VOLUME_STATS,
please verify it--> this can be in new PR

2021-11-02 07:57 UTC, arahamad commented on pkg/ibmcsidriver/node.go
> +	defaultFsType = "nfs"
check if we really using it or not?

2021-11-02 07:57 UTC, arahamad commented on pkg/ibmcsidriver/node.go
> +	mnt := volumeCapability.GetMount()
please verify and update this code

2021-11-02 07:57 UTC, arahamad commented on pkg/ibmcsidriver/node_helper.go
>  func (csiNS *CSINodeServer) processMount(ctxLogger *zap.Logger, requestID, stagingTargetPath, targetPath, fsType string, options []string) (*csi.NodePublishVolumeResponse, error) {
Please check this method if we really need to use it or not

2021-11-02 07:57 UTC, arahamad commented on tests/sanity/sanity_test.go
> +func createTargetDir(targetPath string) error {
check if this is really required?

2021-11-03 04:56 UTC, prankulmahajan commented on deploy/kubernetes/driver/kubernetes/overlays/stage/controller-server-images.yaml
> +          image: icr.io/obs/armada-storage-secret:v1.1.2
Don't think we require the secret-sidecar references.

2021-11-03 05:06 UTC, prankulmahajan approved these changes
lgtm

2021-11-03 08:42 UTC, arahamad approved these changes
review comments are here we will sync-up again 
 https://github.ibm.com/alchemy-containers/armada-storage/issues/2578

2021-11-03 08:48 UTC, merged